# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameBoard.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(310, 304)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setMinimumSize(QtCore.QSize(310, 304))
        Frame.setMaximumSize(QtCore.QSize(310, 304))
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.column_0 = QtWidgets.QPushButton(Frame)
        self.column_0.setEnabled(True)
        self.column_0.setGeometry(QtCore.QRect(0, 0, 64, 304))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column_0.sizePolicy().hasHeightForWidth())
        self.column_0.setSizePolicy(sizePolicy)
        self.column_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.column_0.setStyleSheet("background-image: url(:/fields/empty_column.png);\n"
"background-color: rgb(85, 85, 255);")
        self.column_0.setText("")
        self.column_0.setIconSize(QtCore.QSize(60, 300))
        self.column_0.setAutoRepeatDelay(300)
        self.column_0.setDefault(False)
        self.column_0.setFlat(False)
        self.column_0.setObjectName("column_0")
        self.column_1 = QtWidgets.QPushButton(Frame)
        self.column_1.setEnabled(True)
        self.column_1.setGeometry(QtCore.QRect(64, 0, 64, 304))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column_1.sizePolicy().hasHeightForWidth())
        self.column_1.setSizePolicy(sizePolicy)
        self.column_1.setStyleSheet("background-image: url(:/fields/empty_column.png);\n"
"background-color: rgb(85, 85, 255);")
        self.column_1.setText("")
        self.column_1.setIconSize(QtCore.QSize(60, 300))
        self.column_1.setAutoRepeatDelay(300)
        self.column_1.setDefault(False)
        self.column_1.setFlat(False)
        self.column_1.setObjectName("column_1")
        self.column_2 = QtWidgets.QPushButton(Frame)
        self.column_2.setEnabled(True)
        self.column_2.setGeometry(QtCore.QRect(128, 0, 64, 304))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.column_2.sizePolicy().hasHeightForWidth())
        self.column_2.setSizePolicy(sizePolicy)
        self.column_2.setStyleSheet("background-image: url(:/fields/empty_column.png);\n"
"background-color: rgb(85, 85, 255);")
        self.column_2.setText("")
        self.column_2.setIconSize(QtCore.QSize(60, 300))
        self.column_2.setAutoRepeatDelay(300)
        self.column_2.setDefault(False)
        self.column_2.setFlat(False)
        self.column_2.setObjectName("column_2")
        self.field_column_0 = QtWidgets.QFrame(Frame)
        self.field_column_0.setGeometry(QtCore.QRect(0, 0, 64, 302))
        self.field_column_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.field_column_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.field_column_0.setObjectName("field_column_0")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.field_column_0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.field_0_2 = QtWidgets.QPushButton(self.field_column_0)
        self.field_0_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_2.sizePolicy().hasHeightForWidth())
        self.field_0_2.setSizePolicy(sizePolicy)
        self.field_0_2.setMinimumSize(QtCore.QSize(64, 63))
        self.field_0_2.setMaximumSize(QtCore.QSize(64, 63))
        self.field_0_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_2.setText("")
        self.field_0_2.setFlat(False)
        self.field_0_2.setObjectName("field_0_2")
        self.verticalLayout.addWidget(self.field_0_2)
        self.field_0_3 = QtWidgets.QPushButton(self.field_column_0)
        self.field_0_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_3.sizePolicy().hasHeightForWidth())
        self.field_0_3.setSizePolicy(sizePolicy)
        self.field_0_3.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_3.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_3.setText("")
        self.field_0_3.setFlat(False)
        self.field_0_3.setObjectName("field_0_3")
        self.verticalLayout.addWidget(self.field_0_3)
        self.field_0_1 = QtWidgets.QPushButton(self.field_column_0)
        self.field_0_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_1.sizePolicy().hasHeightForWidth())
        self.field_0_1.setSizePolicy(sizePolicy)
        self.field_0_1.setMinimumSize(QtCore.QSize(64, 63))
        self.field_0_1.setMaximumSize(QtCore.QSize(64, 63))
        self.field_0_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_1.setText("")
        self.field_0_1.setFlat(False)
        self.field_0_1.setObjectName("field_0_1")
        self.verticalLayout.addWidget(self.field_0_1)
        self.field_0_4 = QtWidgets.QPushButton(self.field_column_0)
        self.field_0_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_4.sizePolicy().hasHeightForWidth())
        self.field_0_4.setSizePolicy(sizePolicy)
        self.field_0_4.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_4.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_4.setText("")
        self.field_0_4.setFlat(False)
        self.field_0_4.setObjectName("field_0_4")
        self.verticalLayout.addWidget(self.field_0_4)
        self.field_0_0 = QtWidgets.QPushButton(self.field_column_0)
        self.field_0_0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_0.sizePolicy().hasHeightForWidth())
        self.field_0_0.setSizePolicy(sizePolicy)
        self.field_0_0.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_0.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_0.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_0.setText("")
        self.field_0_0.setFlat(False)
        self.field_0_0.setObjectName("field_0_0")
        self.verticalLayout.addWidget(self.field_0_0)
        self.field_column_1 = QtWidgets.QFrame(Frame)
        self.field_column_1.setGeometry(QtCore.QRect(64, 0, 64, 302))
        self.field_column_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.field_column_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.field_column_1.setObjectName("field_column_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.field_column_1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.field_0_5 = QtWidgets.QPushButton(self.field_column_1)
        self.field_0_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_5.sizePolicy().hasHeightForWidth())
        self.field_0_5.setSizePolicy(sizePolicy)
        self.field_0_5.setMinimumSize(QtCore.QSize(64, 63))
        self.field_0_5.setMaximumSize(QtCore.QSize(64, 63))
        self.field_0_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);")
        self.field_0_5.setText("")
        self.field_0_5.setFlat(False)
        self.field_0_5.setObjectName("field_0_5")
        self.verticalLayout_2.addWidget(self.field_0_5)
        self.field_0_6 = QtWidgets.QPushButton(self.field_column_1)
        self.field_0_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_6.sizePolicy().hasHeightForWidth())
        self.field_0_6.setSizePolicy(sizePolicy)
        self.field_0_6.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_6.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_6.setText("")
        self.field_0_6.setFlat(False)
        self.field_0_6.setObjectName("field_0_6")
        self.verticalLayout_2.addWidget(self.field_0_6)
        self.field_0_7 = QtWidgets.QPushButton(self.field_column_1)
        self.field_0_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_7.sizePolicy().hasHeightForWidth())
        self.field_0_7.setSizePolicy(sizePolicy)
        self.field_0_7.setMinimumSize(QtCore.QSize(64, 63))
        self.field_0_7.setMaximumSize(QtCore.QSize(64, 63))
        self.field_0_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_7.setText("")
        self.field_0_7.setFlat(False)
        self.field_0_7.setObjectName("field_0_7")
        self.verticalLayout_2.addWidget(self.field_0_7)
        self.field_0_8 = QtWidgets.QPushButton(self.field_column_1)
        self.field_0_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_8.sizePolicy().hasHeightForWidth())
        self.field_0_8.setSizePolicy(sizePolicy)
        self.field_0_8.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_8.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);")
        self.field_0_8.setText("")
        self.field_0_8.setFlat(False)
        self.field_0_8.setObjectName("field_0_8")
        self.verticalLayout_2.addWidget(self.field_0_8)
        self.field_0_9 = QtWidgets.QPushButton(self.field_column_1)
        self.field_0_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_0_9.sizePolicy().hasHeightForWidth())
        self.field_0_9.setSizePolicy(sizePolicy)
        self.field_0_9.setMinimumSize(QtCore.QSize(64, 64))
        self.field_0_9.setMaximumSize(QtCore.QSize(64, 64))
        self.field_0_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/fields/red_field_1.png);\n"
"background-image: url(:/fields/empty_field_1.png);\n"
"background-image: url(:/fields/yellow_field_1.png);")
        self.field_0_9.setText("")
        self.field_0_9.setFlat(False)
        self.field_0_9.setObjectName("field_0_9")
        self.verticalLayout_2.addWidget(self.field_0_9)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))

import res_rc
