# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameFrame.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(437, 327)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.boardFrame = QtWidgets.QFrame(Frame)
        self.boardFrame.setMinimumSize(QtCore.QSize(180, 180))
        self.boardFrame.setMaximumSize(QtCore.QSize(300, 300))
        self.boardFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.boardFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.boardFrame.setLineWidth(2)
        self.boardFrame.setObjectName("boardFrame")
        self.gridLayout.addWidget(self.boardFrame, 2, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.statusText = QtWidgets.QLineEdit(Frame)
        self.statusText.setMouseTracking(False)
        self.statusText.setAcceptDrops(False)
        self.statusText.setReadOnly(True)
        self.statusText.setObjectName("statusText")
        self.gridLayout.addWidget(self.statusText, 6, 1, 1, 3)
        self.endButton = QtWidgets.QPushButton(Frame)
        self.endButton.setObjectName("endButton")
        self.gridLayout.addWidget(self.endButton, 7, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 4, 1, 1)
        self.playerPanel = QtWidgets.QWidget(Frame)
        self.playerPanel.setObjectName("playerPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.playerPanel)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentPlayerLabel = QtWidgets.QLineEdit(self.playerPanel)
        self.currentPlayerLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentPlayerLabel.sizePolicy().hasHeightForWidth())
        self.currentPlayerLabel.setSizePolicy(sizePolicy)
        self.currentPlayerLabel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.currentPlayerLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.currentPlayerLabel.setMouseTracking(False)
        self.currentPlayerLabel.setAcceptDrops(False)
        self.currentPlayerLabel.setFrame(True)
        self.currentPlayerLabel.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.currentPlayerLabel.setDragEnabled(False)
        self.currentPlayerLabel.setReadOnly(True)
        self.currentPlayerLabel.setObjectName("currentPlayerLabel")
        self.horizontalLayout.addWidget(self.currentPlayerLabel)
        self.currentPlayerColor = QtWidgets.QPushButton(self.playerPanel)
        self.currentPlayerColor.setEnabled(False)
        self.currentPlayerColor.setMaximumSize(QtCore.QSize(20, 20))
        self.currentPlayerColor.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/fields/color_red.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.currentPlayerColor.setIcon(icon)
        self.currentPlayerColor.setIconSize(QtCore.QSize(20, 20))
        self.currentPlayerColor.setDefault(False)
        self.currentPlayerColor.setFlat(False)
        self.currentPlayerColor.setObjectName("currentPlayerColor")
        self.horizontalLayout.addWidget(self.currentPlayerColor)
        self.currentPlayerType = QtWidgets.QLineEdit(self.playerPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentPlayerType.sizePolicy().hasHeightForWidth())
        self.currentPlayerType.setSizePolicy(sizePolicy)
        self.currentPlayerType.setMaximumSize(QtCore.QSize(45, 16777215))
        self.currentPlayerType.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.currentPlayerType.setMouseTracking(False)
        self.currentPlayerType.setAcceptDrops(False)
        self.currentPlayerType.setReadOnly(True)
        self.currentPlayerType.setObjectName("currentPlayerType")
        self.horizontalLayout.addWidget(self.currentPlayerType)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.playerPanel, 3, 1, 1, 3)

        self.retranslateUi(Frame)
        self.endButton.clicked.connect(Frame.endClicked)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.statusText.setText(_translate("Frame", "STATUS"))
        self.endButton.setText(_translate("Frame", "End"))
        self.currentPlayerLabel.setText(_translate("Frame", "Current Player:"))
        self.currentPlayerType.setText(_translate("Frame", "Human"))
